### ISSUE TITLE
UC Associa Taglie a Colori-Prodotti

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ammazzon-s#18]
Vedere UML Ammazzon.it.Casi d'uso.Casi d'uso accessori.Casi d'uso accessori

**Comment by nicoloabatecola** [comment]
Create entità e componente : ceb770d86ffe6959db9011c226f902f964b6f138

**Comment by nicoloabatecola** [comment]
Html al commit : 6603e75fc32d394aba9cd5e904adaa985ad21b3c

**Comment by capponiFelice92** [comment]
b365b1def571756e60989f93f1759a8bc9a9cf01

**Comment by capponiFelice92** [comment]
60c8fee8279ffb4ae5a3c030958cc91f64c9d308

**Comment by capponiFelice92** [comment]
d70305f9af5104a33132e72a340ef757f260361a

**Comment by capponiFelice92** [comment]
4ed79b6afedef3cb1af34d899406e8aee867fad4

**Comment by capponiFelice92** [comment]
d11b8ccc8f07b17b4808deceb951e7771070d9c8
