### ISSUE TITLE
Menu sinistro con errori

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ammazzon-s#28]
Cambiare Anagrafica Taglia in Anagrafica Taglie, Anagrafica Utente Registrato in Anagrafica Utenti Registrati, Associa Taglie Prodotti Colori in Associa Taglie, Associa i Colori Ai Prodotti in Associa Colori.

Cambiare PROGAMMATORI ESPERTI in PROGRAMMATORI ESPERTI

**Comment by ValeriaCom** [comment]
risolto al commit 16166790849531a478bfa2b4d3ddfee677c868e3
