### ISSUE TITLE
Anagrafica Colori problemi in modifica

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ammazzon-s#33]
Selezionare un colore, modifica, modificare il valore, cliccare annulla -> il valore rimane modificato sia nel campo sia nella tabella (ma non sul DB). 
Comportamento corretto: la tabella e i campi di input mantengono il valore prima della modifica

**Comment by Giulia2Gargano** [comment]
Risolto al commit 6e7942c100deb6f4200620963e217419bd97f2e3. 
Risulta ancora troppo lento con dati di test generati automaticamente.
