### ISSUE TITLE
UC Gestione Prodotti

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ammazzon-s#38]
Vedere Ammazzon.it.Casi d'uso.Casi d'uso Catalogo.Casi d'uso Catalogo

**Comment by matteo2025** [comment]
implementata parte client d6ec5f4cf80bfda105048090cb64ca7dcb2f5f48

**Comment by nicoloabatecola** [comment]
prima parte server : 4360261c48e5774d3c6acabb78ee4f8f8db5540f

**Comment by matteo2025** [comment]
ricerca e modifica di nuovo funzionanti 9964fd3f08ab88e3456ceee89beb7894881ddd57

**Comment by matteo2025** [comment]
aggiustata ricerca 6471c4fff10d2d0bbe79988e395d3346a1a38ca7

**Comment by matteo2025** [comment]
implementata cancellazione d83cd4e6d7f7b0ea27c5a48ed024acf93b823220

**Comment by matteo2025** [comment]
270c8d295b28f2c37f8a7193d33ca603b7cbe0e8
