### ISSUE TITLE
Creare CSS lato client

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ammazzon-s#4]
thema.css, stessa struttura del precedente

**Comment by nicoloabatecola** [comment]
Prima parte : 1afa8e1c1bbc83ed5b9f42200ef1987bfacac775

**Comment by nicoloabatecola** [comment]
Home Page al commit : 306c417d02609c3a2f66baf9463bfae7c1da3909

**Comment by nicoloabatecola** [comment]
Corretti alcuni bug al commit : 5eaf78a9fe2d1bfbcefd0e727e79b598cc25eef5

**Comment by nicoloabatecola** [comment]
Rifatto da 0 al commit : 2d7c28c73abd3b734a52eb24422ba51be06cb292
