### ISSUE TITLE
Creare entità lato server, con associazioni

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ammazzon-s#5]

**Comment by matteo2025** [comment]
iniziato acdc48fd4a696edf11dfc337842166e0343f2b5f

**Comment by matteo2025** [comment]
bc8ba6cafdd68c5228dd8c64ee57f0c7b4408920

**Comment by matteo2025** [comment]
fdfc916d4a8a1a36a8412890c917a28ed4afcf9c

**Comment by matteo2025** [comment]
Risolto: 209c2ef78466f1eb6fc6035a19e707aa341dc4fb

**Comment by matteo2025** [comment]
creati repository 58994b8eb224c7fa3480dd71955635388b44725c
