### ISSUE TITLE
Creare generatore dati di test

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ammazzon-s#6]
Almeno tre utenti registrati, almeno 1000 prodotti, almeno tre colori, almeno tre taglie, prodotti collegati come segue:

Prodotti con id % 3 == 0 -> 1 colore e 2 taglie
Prodotti con id % 3 == 1 -> 1 colore e tre taglie
Prodotti con id % 3 == 2 -> 2 colori e tre taglie per colore

La scelta colori e taglie deve essere fatta a caso.

**Comment by nicoloabatecola** [comment]
Creazione prodotti al commit : e9d8e4dd92c8c6f3f178944314eabdb3f4aa7874

**Comment by nicoloabatecola** [comment]
Creato metodo associaProdottoColore al commit: 93c0fa477716123eebaed3f6298ef6c7a37a6c8e

**Comment by matteo2025** [comment]
eb1d9ad8cd88097b296cda932847f36d124ab793

**Comment by capponiFelice92** [comment]
96cad729c682a3e7cbbce3fd5e04f6b6bf35b166

**Comment by capponiFelice92** [comment]
ee27c9308bc9e6ec5530a8c51077c3a3fb419e46
