### ISSUE TITLE
Gestire CRUD utenti registrati

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ammazzon-s#7]
Per inserire, modificare, cancellare e ricercare utenti registrati

**Comment by daniele-bit** [comment]
Implementato CRUD al commit eeecc1d4d4f0ae60728d43fad0a20da1e0fc5e80

**Comment by luca-lezzerini** [comment]
Vedere UML Ammazzon.it.Casi d'uso.Casi d'uso accessori.Casi d'uso accessori

**Comment by marcobonaccorso** [comment]
Gestire CRUD utenti registrati #7

Terminato al commit e10377f26acade5683897a9221eeab5ed4ce6493
